# ------------------- General Options -------------------------
description                  : AgentFormer (Before DLow)
results_root_dir             : results
seed                         : 1


# ------------------- Dataset ----------------------
dataset_name: ethucy
dataset_split: eth
trial: 0

# ------------------- Common Settings -------------------------
obs_len: 8
pred_len: 12
num_nbr: 4
view_range: 20.0
view_angle: 1.0
social_range: 2.0

env_range: 10.0
env_resol: 0.1
patch_size: 16
scene: None

# ------------------- Embedding -------------------------
#map_emb_act: 'gelu'
env_emb: []

# ------------------- Decoding --------------------------

# ------------------- Trajectory-To-Goal Prediction -------------------------

past_frames                  : 8
future_frames                : 12
min_past_frames              : 8
min_future_frames            : 12

traj_scale                   : 2
motion_dim                   : 2
forecast_dim                 : 2





# ------------------- Goal Prediction Prediction -------------------------

model_id: social_bert_plus
input_type: ['scene_norm', 'vel']
pred_type: 'scene_norm'
sn_out_type: 'norm'
max_train_agent: 32
pos_concat: true
rand_rot_scene: true

context_encoder:
  nlayer: 2

goal_hidden: 64
goal_latent: 64


# ------------------- CVAE -------------------------

nz                           : 32
learn_prior: true
sample_k                     : 20

# ------------------- Training Parameters -------------------------

lr                           : 1.e-4
loss_cfg:
  mse:
    weight: 1.0
  kld:
    weight: 1.0
    min_clip: 2.0
  sample:
    weight: 1.0
    k: 20

num_epochs                   : 100
lr_fix_epochs                : 10
lr_scheduler: 'step'
decay_step: 10
decay_gamma: 0.5
print_freq                   : 20
model_save_freq              : 10

